"""Development oracle only: generate pinned OCIO reference fixtures.

Run with the official OpenColorIO 2.5.2 Python wheel on PYTHONPATH.
VibeColor's executable does not use Python or these bindings.
"""
import json
from pathlib import Path
import PyOpenColorIO as ocio

assert ocio.GetVersion() == "2.5.2"
config_name = "studio-config-v4.0.0_aces-v2.0_ocio-v2.5"
config = ocio.Config.CreateFromBuiltinConfig(config_name)
linear = "Linear Rec.709 (sRGB)"
cases = []


def add(label, transform, inputs, processor):
    cpu = processor.getDefaultCPUProcessor()
    outputs = [cpu.applyRGBA(p) for p in inputs]
    cases.append({"label": label, "transform": transform,
                  "input": inputs, "expected": outputs})


for source, destination in [
    (linear, "sRGB Encoded Rec.709 (sRGB)"),
    ("ACEScg", linear),
    ("ARRI LogC4", linear),
    ("S-Log3 S-Gamut3.Cine", linear),
    ("DaVinci Intermediate WideGamut", linear),
]:
    inputs = [[0., 0., 0., 1.], [.18, .18, .18, .25],
              [.6, .3, .1, .75], [1., 1., 1., 0.], [-.05, .2, .4, 1.]]
    add(f"{source} -> {destination}",
        {"type": "color_space", "source": source, "destination": destination},
        inputs, config.getProcessor(source, destination))

for display, view in [
    ("sRGB - Display", "ACES 2.0 - SDR 100 nits (Rec.709)"),
    ("sRGB - Display", "Un-tone-mapped"),
    ("Display P3 - Display", "ACES 2.0 - SDR 100 nits (P3 D65)"),
    ("Rec.2100-PQ - Display", "ACES 2.0 - HDR 1000 nits (Rec.2020)"),
]:
    inputs = [[0., 0., 0., 1.], [.18, .18, .18, .25],
              [.6, .3, .1, .75], [1., 1., 1., 0.],
              [16., 4., .1, 1.], [-.05, .2, .4, 1.]]
    add(view, {"type": "display_view", "source": linear,
               "display": display, "view": view, "inverse": False},
        inputs, config.getProcessor(linear, display, view, ocio.TRANSFORM_DIR_FORWARD))

fixture = {"oracle": "Official OpenColorIO Python wheel, independent of ocio-rs",
           "engine_version": ocio.GetVersion(), "config": config_name, "cases": cases}
path = Path(__file__).resolve().parent.parent / "crates/ocio/tests/fixtures/ocio-2.5.2.json"
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(cases)} conversion cases to {path}")

# Independent custom-context / package fixture. The same config is then loaded
# by Rust from the original files and from an OCIOZ with originals deleted.
root = Path(__file__).resolve().parent.parent
custom = ocio.Config.CreateFromFile(str(root / "examples/custom-ocio/config.ocio"))
custom_inputs = [[.18, .4, .6, .3], [1., .18, .001, 1.]]
custom_cases = []
for grade in ["neutral", "warm"]:
    context = ocio.Context()
    context.setWorkingDir(custom.getWorkingDir())
    context.setSearchPath(custom.getSearchPath())
    context.setStringVar("GRADE", grade)
    processor = custom.getProcessor(context, "linear", "Photo sRGB", "Standard", ocio.TRANSFORM_DIR_FORWARD)
    cpu = processor.getDefaultCPUProcessor()
    custom_cases.append({"context": {"GRADE": grade},
                         "input": custom_inputs, "expected": [cpu.applyRGBA(p) for p in custom_inputs]})
custom_fixture = {"oracle": "Official OpenColorIO Python wheel, independent of ocio-rs",
                  "engine_version": ocio.GetVersion(), "cases": custom_cases}
custom_path = path.with_name("custom-ocio-2.5.2.json")
custom_path.write_text(json.dumps(custom_fixture, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(custom_cases)} custom context cases to {custom_path}")

# Native grades: enter a declared process space, grade, and return to the input.
# These outputs are generated by official bindings, never by the Rust wrapper.
grade_cases = []
grade_inputs = [[0., 0., 0., 1.], [.18, .4, .06, .25], [.6, .3, .1, .75],
                [16., 4., .1, 0.], [-.05, .2, .4, 1.]]


def native_grade(cfg, anchor, grade, ctx):
    inverse = grade.get("inverse", False)
    direction = ocio.TRANSFORM_DIR_INVERSE if inverse else ocio.TRANSFORM_DIR_FORWARD
    if grade["type"] == "look":
        transform = ocio.LookTransform(src=anchor, dst=anchor, looks=grade["looks"], direction=direction)
    else:
        group = ocio.GroupTransform()
        group.appendTransform(ocio.ColorSpaceTransform(src=anchor, dst=grade["color_space"], dataBypass=False))
        if grade["type"] == "cdl":
            style = ocio.CDL_ASC if grade["style"] == "asc" else ocio.CDL_NO_CLAMP
            transform = ocio.CDLTransform(slope=grade["slope"], offset=grade["offset"],
                                          power=grade["power"], sat=grade["saturation"],
                                          direction=direction)
            transform.setStyle(style)
        else:
            matrix = [grade["matrix"][r][c] if r < 3 and c < 3 else float(r == c)
                      for r in range(4) for c in range(4)]
            transform = ocio.MatrixTransform(matrix=matrix, offset=grade["offset"] + [0.], direction=direction)
        group.appendTransform(transform)
        group.appendTransform(ocio.ColorSpaceTransform(src=grade["color_space"], dst=anchor, dataBypass=False))
        transform = group
    return cfg.getProcessor(ctx, transform, ocio.TRANSFORM_DIR_FORWARD).getDefaultCPUProcessor()


def grade_case(label, config_source, cfg, anchor, grade, context=None, inputs=grade_inputs):
    context = context or {}
    ctx = ocio.Context()
    ctx.setWorkingDir(cfg.getWorkingDir())
    ctx.setSearchPath(cfg.getSearchPath())
    for key, value in context.items():
        ctx.setStringVar(key, value)
    cpu = native_grade(cfg, anchor, grade, ctx)
    grade_cases.append({"label": label, "config": config_source, "context": context,
                        "transform": {"type": "grade", "source": anchor, "grade": grade},
                        "input": inputs, "expected": [cpu.applyRGBA(p) for p in inputs]})


base_cdl = {"type": "cdl", "slope": [1.05, .94, 1.1], "offset": [-.01, .02, 0.],
            "power": [.95, 1.1, 1.02], "saturation": .8, "style": "no_clamp"}
builtin_source = {"type": "builtin", "name": config_name}
for space, style, inverse in [("ACEScct", "no_clamp", False), ("ACEScct", "no_clamp", True),
                              ("DaVinci Intermediate WideGamut", "no_clamp", False),
                              (linear, "asc", False), (linear, "asc", True), (linear, "no_clamp", False)]:
    grade_case(f"CDL {space} {style} inverse={inverse}", builtin_source, config, linear,
               {**base_cdl, "color_space": space, "style": style, "inverse": inverse})
for inverse in [False, True]:
    grade_case(f"ACEScg matrix inverse={inverse}", builtin_source, config, linear,
               {"type": "matrix", "color_space": "ACEScg", "matrix": [[1.02, .01, 0.], [0., .95, .02], [.03, 0., 1.1]],
                "offset": [.001, -.002, .003], "inverse": inverse})
node_config_path = root / "examples/node-ocio/config.ocio"
node_config = ocio.Config.CreateFromFile(str(node_config_path))
node_source = {"type": "file", "path": "examples/node-ocio/config.ocio"}
for looks, inverse, context in [("+Warm,+SoftContrast", False, {}), ("+Warm,+SoftContrast", True, {}),
                                ("+ContextGrade,+SoftContrast", False, {"GRADE": "neutral"}),
                                ("+ContextGrade,+SoftContrast", False, {"GRADE": "warm"}),
                                ("Unavailable | +Warm", False, {})]:
    grade_case(f"Looks {looks} inverse={inverse} context={context}", node_source, node_config, "linear",
               {"type": "look", "looks": looks, "inverse": inverse}, context)
grade_fixture = {"oracle": "Official OpenColorIO Python wheel, independent of ocio-rs",
                 "engine_version": ocio.GetVersion(), "cases": grade_cases}
grade_path = path.with_name("grades-ocio-2.5.2.json")
grade_path.write_text(json.dumps(grade_fixture, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(grade_cases)} grade cases to {grade_path}")
