[package]
name = "vibecolor-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
rayon.workspace = true
vibecolor-core.workspace = true
vibecolor-color.workspace = true
vibecolor-io.workspace = true
vibecolor-project.workspace = true
vibecolor-ocio.workspace = true

tempfile.workspace = true
schemars.workspace = true
